development:
  adapter: mysql2 
  database: vineyqrd_dev
  pool: 5
  timeout: 5000
  user: root
  password:

test:
  adapter: mysql2 
  database: vineyqrd_dtest
  pool: 5
  timeout: 5000
  user: root
  password:

production:
  adapter: mysql2 
  database: vineyqrd_prod
  pool: 5
  timeout: 5000
  user: root
  password:

